---
- include_tasks: setup-Debian.yml
- include_tasks: configure.yml

- name: Initialize the LineageOS source repository
  shell: repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
  args:
    chdir: "{{ build_dir }}/lineage"
  when: not skip_sync | bool

- name: Download the source code
  shell: repo sync
  args: 
    chdir: "{{ build_dir }}/lineage"
  when: not skip_sync | bool

- name: Prepare the device-specific code
  shell: source build/envsetup.sh && breakfast davinci
  args:
    chdir: "{{ build_dir }}/lineage"
    executable: /bin/bash

- name: Unzip system_dump
  unarchive:
    src: https://dl.lineageosroms.com/davinci/lineage-17.1-20220202-nightly-davinci-signed.zip
    dest: "{{ build_dir }}/system_dump/"
    remote_src: yes
    include:
      - system.transfer.list
      - system.new.dat.br
      - vendor.transfer.list
      - vendor.new.dat.br
      - product.transfer.list
      - product.new.dat.br

- name: Decompress br files
  shell: "brotli --decompress --output={{ item }}.new.dat {{ item }}.new.dat.br"
  args:
    chdir: "{{ build_dir }}/system_dump/"
    creates: "{{ item }}.new.dat"
  loop:
    - system
    - vendor
    - product

- name: Install sdat2img from Git
  git:
    repo: https://github.com/xpirt/sdat2img
    dest: "{{ build_dir }}/system_dump/sdat2img"

- name: Create system images
  shell: "python sdat2img/sdat2img.py {{ item }}.transfer.list {{ item }}.new.dat {{ item }}.img"
  args:
    chdir: "{{ build_dir }}/system_dump/"
    creates: "{{ item }}.img"
  loop:
    - system
    - vendor
    - product

- name: Create system directory
  file:
    path: "{{ build_dir }}/system_dump/system/"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Mount system image
  become: yes
  shell: |
    mount system.img system/
    mount vendor.img system/vendor/
    mount product.img system/product/
  args:
    chdir: "{{ build_dir }}/system_dump"

- name: Extract proprietary blobs
  shell: ./extract-files.sh /android/system_dump/
  args:
    chdir: "{{ build_dir }}/lineage/device/xiaomi/davinci/"

- name: Start the build
  shell: "source build/envsetup.sh && croot && brunch davinci >> {{ build_dir }}/build.log"
  args:
    chdir: "{{ build_dir }}/lineage"
    executable: /bin/bash
