---
- name: Install the build packages
  become: yes
  apt: 
    name:
      - bc
      - bison
      - brotli
      - build-essential
      - ccache
      - curl
      - flex
      - g++-multilib
      - gcc-multilib
      - git
      - gnupg
      - gperf
      - imagemagick
      - lib32ncurses5-dev
      - lib32readline-dev
      - lib32z1-dev
      - libelf-dev
      - liblz4-tool
      - libncurses5
      - libncurses5-dev
      - libsdl1.2-dev 
      - libssl-dev 
      - libxml2 
      - libxml2-utils 
      - lzop 
      - patchelf
      - pngcrush 
      - python-is-python3
      - rsync
      - schedtool 
      - squashfs-tools 
      - xsltproc
      - zip 
      - zlib1g-dev
    state: present
    update_cache: yes

- name: Install the repo command
  become: yes
  get_url: 
    url: https://storage.googleapis.com/git-repo-downloads/repo
    dest: /usr/local/bin/repo
    mode: '0755'
